[workspace]
resolver = "2"
members = [
    "api/account_manager",
    "api/airdrop",
    "api/general",
    "api/newbie_reward",
    "api/wallet",
    "common",
    "scanner",
    "models",
    "blockchain"
]

exclude = [
    "doc",
    "tools"
]
