[package]
name = "models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-http-server = "12.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.10.1"
untrusted = "0.6.2"
##rust_decimal = "1.0.1"
num = "0.2"
jsonrpc-client-http = "0.5.0"
jsonrpc-client-core = "0.5.0"
slog-term = "2.4.0"
slog-async = "2.3.0"
lazy_static = "1.3.0"
postgres = {version = "0.16.0-rc.2",features=["with-serde_json-1"]}
serde_json = "1.0.40"
rust_decimal = { version = "1.0.3", features = ["postgres"] }
rustc-serialize = "0.3.18"
chrono = "0.4"
ethers-core = "0.6.0"
env_logger = "0.7.1"
anyhow = "1.0.53"
common = {path = "../common"}
tracing = "0.1.27"